services:
  funnel-scheduler:
    build:
      context: ./bot
      dockerfile: ./src/scheduler/Dockerfile
    container_name: funnel-scheduler
    env_file: .env
    network_mode: host
    volumes:
      - ./bot:/app
      - ./var/log:/app/var/log

volumes:
  scheduler_logs: