services:
  funnel-task-scheduler:
    build:
      context: ./bot
      dockerfile: ./src/processing/schedulers/task_scheduler/Dockerfile
    container_name: funnel-task-scheduler
    env_file: .env
    network_mode: host
    volumes:
      - ./bot:/app
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  funnel-payment-checker-scheduler:
    build:
      context: ./bot
      dockerfile: ./src/processing/schedulers/payment_checker_scheduler/Dockerfile
    container_name: funnel-payment_checker_schedule
    env_file: .env
    network_mode: host
    volumes:
      - ./bot:/app
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  funnel-user-consumer:
    build:
      context: ./bot
      dockerfile: ./src/processing/workers/user_worker/Dockerfile
    container_name: user-consumer
    env_file: .env
    network_mode: host
    volumes:
      - ./bot:/app
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped


volumes:
  scheduler_logs: