server {
    listen 80;
    server_name rafassiaofusa.fvds.ru;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name rafassiaofusa.fvds.ru;

    ssl_certificate /etc/letsencrypt/live/rafassiaofusa.fvds.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rafassiaofusa.fvds.ru/privkey.pem;

    location /webhook/yookassa {
        proxy_pass http://webhook:8000/webhook/yookassa;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
